config/routes.rb
Rails.application.routes.draw do
  get 'resumes/index'
  get 'resumes/new'
  get 'resumes/create'
  get 'resumes/destroy'
  get 'resumes/:id', to: 'resumes#destroy'
  
  post 'conciliacion', to: 'resumes#conciliacion'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :resumes, only: [:index, :new, :create, :destroy]   
  root "resumes#index"  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bus_ticket.rb
class BusTicket < ActiveRecord::Base
    self.abstract_class = true
    self.table_name = 'tickets'
    establish_connection :etn
  end

app/models/resume.rb
class Resume < ApplicationRecord
    mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.   
    validates :name, presence: true # Make sure the owner's name is present.   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/resumes_controller.rb
require 'csv'

class ResumesController < ApplicationController
  def index   
    @resumes = Resume.all;   
  end   
    
  def new   
    @resume = Resume.new;  
  end   
    
  def create   
    @resume = Resume.new(resume_params);   
       
    if @resume.save   
      redirect_to resumes_path, notice: "Successfully uploaded.";   
    else   
      render "new";  
    end   
  end   
    
  def destroy   
    @resume = Resume.find(params[:id]);   
    @resume.destroy;  
    redirect_to resumes_path, notice:  "Successfully deleted.";  
  end
  
  def conciliacion
    review_report(params[:report_resume], params[:logs_resume][:name]);
  end

  def print_message
    respond_to do |format|
        format.js; 
    end
  end
    
 private   
  def resume_params   
    params.require(:resume).permit(:name, :attachment, :resume_type);   
  end
  
  def review_report(report_resume, logs_resume)
    @report_entity = Resume.find_by(name: report_resume);
    @logs_entity = Resume.find_by(name: logs_resume);
    
    results = [];
    i = 0;

    CSV.foreach(("public#{@report_entity.attachment}"), headers: true, col_sep: ",") do |row_report|
      finded = false;
      CSV.foreach(("public#{@logs_entity.attachment}"), headers: true, col_sep: ",") do |row_logs|
        if row_logs[1].include? row_report[3];
          CSV.foreach(("public#{@logs_entity.attachment}"), headers: true, col_sep: ",") do |row_logs_second|
            if ((row_logs_second[1].include? row_logs[1][8, 36]) && (row_logs_second[1].include? "pending"))
              token_index = row_logs_second[1].index("token")
              results[i] = {transporter_key: row_report[3], log: row_logs[1], token: row_logs_second[1][token_index+8, 11]};
              finded = true;
              i += 1;
            end
          end
        end
      end 
      if finded == false
        results[i] = {
          transporter_key: row_report[3], 
          log: "No se encontraron registros (posible doble reservación)", 
          token: "No se encontraron registros (posible doble reservación)"};
        i += 1;
      end
    end 
    csv_generation(results, report_resume);
  end

  def csv_generation(results, report_resume)
    CSV.open("#{Rails.root}/public/generations/#{report_resume}_reviewed.csv", "wb") do |csv|
        results.each do |result|
          csv << [result[:transporter_key], result[:log], result[:token]]
        end
    end
    
    resume_params = {
      name: "#{report_resume}_reviewed",
      attachment: "#{Rails.root}/public/generations/#{report_resume}_reviewed.csv"
    }

    Resume.create!(
      attachment: ActionDispatch::Http::UploadedFile.new(
        tempfile: File.open("#{Rails.root}/public/generations/#{report_resume}_reviewed.csv"), 
        filename: "#{report_resume}_reviewed.csv",
        content_type: 'text/csv'
      ),
      name: "#{report_resume}_reviewed.csv"
    )

  end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
    def revision
        puts "REVISION"
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>   
<html>   
    <head>   
        <title>File Uploading</title>   
            <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>   
            <%= csrf_meta_tags %>   
    </head>      
    <body>
        <div>
            <%= render partial: "navbar", locals: { myvar: @val } %>
        </div>
        <div>   
            <%= yield %>   
        </div>   
    </body>
</html>  

app/views/resumes/_navbar.html.erb
<nav id="navbar">
  <a id="navbar" class="title" href="/">Management App</a>
</nav>

app/views/resumes/conciliacion.html.erb
<div id="conciliacion">
  <h2 id="conciliacion" class="header">¡Resumen creado exitosamente!</h2>
  <%= image_tag('ardilla_sombrero.jpg', draggable: "true", class: "ardilla") %>
</div>

app/views/resumes/create.html.erb
<h1>Resumes#create</h1>
<p>Find me in app/views/resumes/create.html.erb</p>

app/views/resumes/destroy.html.erb
<h1>Resumes#destroy</h1>
<p>Find me in app/views/resumes/destroy.html.erb</p>

app/views/resumes/index.html.erb
<div class="container">   
    <% if !flash[:notice].blank? %>   
       <div>   
          <%= flash[:notice] %>   
       </div>   
    <% end %>   
      
    <br>   
      
    <%= link_to "New Resume", new_resume_path %>   
    <br>   
    <br>   
      
    <table border="3" class="table">   
        <thead>   
            <tr>   
                <th>File name</th>   
                <th>Download Link</th>   
                <th>Reconciliation Summary</th>
                <th>Action</th>   
            </tr>   
       </thead>   
          
       <tbody>   
            <% @resumes.each do |resume| %>  
                <tr>   
                    <td><%= resume.name %></td>   
                    <td><%= link_to "Download", resume.attachment_url %></td>   
                    <td>
                        <% if resume.resume_type == 'Report' %> 
                            <%= form_tag("conciliacion", method: "post") do %>
                                <%= label_tag(:logs_resume, "Logs resume:") %>
                                <%= collection_select(:logs_resume, :name, Resume.where(resume_type: "Logs"), :name, :name) %>
                                <%= hidden_field_tag :report_resume, resume.name %>
                                <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
                                <%= submit_tag("Review report") %>
                            <% end %>
                        <% end %>    
                    </td>
                    <td><%= link_to "Delete",  resume, method: :delete, confirm: "Are you sure you want to delete #{resume.name}?" %></td>   
                </tr>   
          <% end %>   
       </tbody>     
    </table>   
</div>  

app/views/resumes/new.html.erb
<div class="container">   
    <% if !@resume.errors.empty? %>   
        <div>        
            <ul>   
                <% @resume.errors.full_messages.each do |msg| %>   
                    <li><%= msg %></li> 
                <% end %>   
            </ul>  
        </div>
    <% end %>       
      
    <div>   
       <%= form_for @resume, html: { multipart: true } do |f| %>   
          <%= f.label :name %>   
          <%= f.text_field :name %>   
          <br><br>   
          <%= f.label :attachment %>   
          <%= f.file_field :attachment %>   
          <br><br>
          <%= f.label :resume_type %>   
          <%= f.select(:resume_type, options_for_select([ "Report", "Logs" ])) %>
          <br><br>
          <%= f.submit "Save" %>   
       <% end %>   
    </div>   
</div>  